<?php
$z[0]=Array("pagestyle","",0,84);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="";
$z[0][4]['ddmaxwidth']="";
$z[0][4]['row']="";
$z[0][4]['col']="";
$z[0][4]['value']="3";
$z[1]=Array("img"," /uploads/allimg/180315/1-1P315101453.jpg ",86,233);
$z[1][4]['ddimg']="/uploads/allimg/180315/1-1P315101453.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="1920";
$z[1][4]['height']="1440";
$z[2]=Array("img"," /uploads/allimg/180315/1-1P315101454.jpg ",235,382);
$z[2][4]['ddimg']="/uploads/allimg/180315/1-1P315101454.jpg";
$z[2][4]['text']="";
$z[2][4]['width']="1920";
$z[2][4]['height']="1440";

?>