<?php
$z[0]=Array("pagestyle","",0,88);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="0";
$z[0][4]['ddmaxwidth']="0";
$z[0][4]['row']="0";
$z[0][4]['col']="0";
$z[0][4]['value']="3";
$z[1]=Array("img"," /uploads/allimg/180315/1-1P315101457.jpg ",90,292);
$z[1][4]['ddimg']="/uploads/allimg/180315/1-1P315101457-lp.jpg";
$z[1][4]['text']="认筹2-4万，如果买四楼成功，可冲低2万";
$z[1][4]['width']="1920";
$z[1][4]['height']="1440";
$z[2]=Array("img"," /uploads/allimg/180315/1-1P315101458.jpg ",294,496);
$z[2][4]['ddimg']="/uploads/allimg/180315/1-1P315101458-lp.jpg";
$z[2][4]['text']="认筹2-4万，如果买四楼成功，可冲低2万";
$z[2][4]['width']="1920";
$z[2][4]['height']="1440";

?>