<?php
$z[0]=Array("pagestyle","",0,88);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="0";
$z[0][4]['ddmaxwidth']="0";
$z[0][4]['row']="0";
$z[0][4]['col']="0";
$z[0][4]['value']="3";
$z[1]=Array("img"," /uploads/allimg/180315/1-1P3150R926.jpg ",90,242);
$z[1][4]['ddimg']="/uploads/allimg/180315/1-1P3150R926-lp.jpg";
$z[1][4]['text']="外观";
$z[1][4]['width']="800";
$z[1][4]['height']="686";
$z[2]=Array("img"," /uploads/allimg/180315/1-1P3150R927.jpg ",244,396);
$z[2][4]['ddimg']="/uploads/allimg/180315/1-1P3150R927-lp.jpg";
$z[2][4]['text']="外观";
$z[2][4]['width']="800";
$z[2][4]['height']="450";

?>