<div class="interest-item">
                            <a href="[field:arcurl/]" target="_blank">
                            <img src="[field:litpic/]" height="240" width="320" alt="[field:title/]"/>
                            <div class="interest-title">
                                <span class="glyphicon glyphicon-map-marker"></span>
                                [field:typename/]                                
                                <div class="tab-list pull-right"></div>
                            </div>
                            <div  class="interest-info">
                                <label>[field:title/]</label>
                                <div>
                                    <label class="unit pull-right"><span>[field:qijia/]</span> 元/㎡
                                    </label>
                                </div>
                            </div>
                            </a>
                        </div>