<?php
$z[0]=Array("pagestyle","",0,84);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="";
$z[0][4]['ddmaxwidth']="";
$z[0][4]['row']="";
$z[0][4]['col']="";
$z[0][4]['value']="1";
$z[1]=Array("img"," /uploads/allimg/180315/1-1P3150Q554.jpg ",86,241);
$z[1][4]['ddimg']="/uploads/allimg/180315/1-1P3150Q554.jpg";
$z[1][4]['text']="地理位置";
$z[1][4]['width']="800";
$z[1][4]['height']="686";
$z[2]=Array("img"," /uploads/allimg/180315/1-1P3150Q555.jpg ",243,398);
$z[2][4]['ddimg']="/uploads/allimg/180315/1-1P3150Q555.jpg";
$z[2][4]['text']="地理位置";
$z[2][4]['width']="800";
$z[2][4]['height']="450";

?>