<a href="[field:arcurl/]" target="_blank"><img title="[field:title/]" src="[field:litpic/]" style="border-width:0px;">
                <div class="lphot_n_txt">
                  <p class="title" title="[field:title/]"><b>[field:title/]</b><span class="txt_city sz16">[[field:typename/]]</span></p>
                  <p class="price sz16">起价：<font class="jg">[field:qijia/]元</font>/㎡ &nbsp;&nbsp;&nbsp; 均价：<font class="jg">[field:junjia/]元</font>/㎡</p>
                </div>
                </a>