<div class="actionList-li">
                <p class="actionTit li_[field:global name=autoindex runphp='yes']@me=@me+1;[/field:global]"><a class="focus_link" href="[field:arcurl/]">[field:title/]...</a></p>
                <div class="actionDetailed"> <a target="_blank" class="focus_link" href="[field:arcurl/]"><img class="actionDetailed-img" src="[field:litpic/]" alt="[field:title/]" width="240" height="180" border="0"></a>
                  <p class="actionDetailed-js">[field:info/]...</p>
                </div>
              </div>