<div class="actionList-li action">
                <p class="actionTit li_1"><a class="focus_link" href="[field:arcurl/]">[field:title/]...</a></p>
                <div class="actionDetailed"> <a target="_blank" class="focus_link" href="[field:arcurl/]"><img class="actionDetailed-img" src="[field:litpic/]" alt="[field:title/]" width="240" height="180" border="0"></a>
                  <p class="actionDetailed-js">[field:info/]...</p>
                </div>
              </div>