<?php
$z[0]=Array("pagestyle","",0,88);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="0";
$z[0][4]['ddmaxwidth']="0";
$z[0][4]['row']="0";
$z[0][4]['col']="0";
$z[0][4]['value']="3";
$z[1]=Array("img"," /uploads/allimg/160124/1-160124192422.jpg ",90,240);
$z[1][4]['ddimg']="/uploads/allimg/160124/1-160124192422-lp.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="837";
$z[1][4]['height']="590";
$z[2]=Array("img"," /uploads/allimg/160124/1-160124192423.jpg ",242,392);
$z[2][4]['ddimg']="/uploads/allimg/160124/1-160124192423-lp.jpg";
$z[2][4]['text']="";
$z[2][4]['width']="830";
$z[2][4]['height']="590";
$z[3]=Array("img"," /uploads/allimg/160124/1-160124192424.jpg ",394,544);
$z[3][4]['ddimg']="/uploads/allimg/160124/1-160124192424-lp.jpg";
$z[3][4]['text']="";
$z[3][4]['width']="823";
$z[3][4]['height']="590";
$z[4]=Array("img"," /uploads/allimg/160124/1-160124192427.jpg ",546,696);
$z[4][4]['ddimg']="/uploads/allimg/160124/1-160124192427-lp.jpg";
$z[4][4]['text']="";
$z[4][4]['width']="861";
$z[4][4]['height']="590";

?>