<li> <a href="[field:arcurl/]" title="[field:title/]"><img src="[field:litpic/]" alt="[field:title/]" class="fl" width="100" height="75" border="0"></a>
              <div class="cf">
                <h4><a href="[field:arcurl/]" title="[field:title/]">[field:title/]</a></h4>
                <p class="new_detail">[field:info/]... <a href="[field:arcurl/]" class="fr" title="[field:title/]">[查看详情]</a> </p>
              </div>
            </li>