<div class="house-item">
                                <div class="buy-type">
                                    <img width="30" src="/skin/images/tuan.png" alt="团购楼盘"/>
                                    <img width="30" src="/skin/images/du.png" alt="独家代理"/>
                                </div>
                                 <a href="[field:arcurl/]" target="_blank">
                                <img width="200" height="150" src="[field:litpic/]" alt="[field:title/]">
                                 </a>
                                <h5>
                                     <a href="[field:arcurl/]" target="_blank">[field:title/]</a>
                                </h5>
								<h5 class="product-list">
                                    <span>[field:tyouhui/]</span>
                                </h5>
								    <label class="marker">
                                    <span class="glyphicon glyphicon-map-marker"></span>
                                    [field:lopandizhi/]                             
                                    </label>
                                <label class="unit-title pull-right">
                                    <span>[field:qijia/]</span> 元/㎡
                                    </label>
                                <br/>
                                [field:id function=GetTags(@me)/]    
                            </div>