<div class="interest-item ng-scope"> <a href="[field:arcurl/]" target="_blank"> <img src="[field:litpic/]" height="240" width="320" alt="">
            <div class="interest-title">[field:typename/]
            <div class="tab-list pull-right"> </div>
          </div>
            <div class="interest-info">
            <label>[field:title/]</label>
            <div>
                <label class="unit pull-right"><span>[field:qijia/]</span>元/m²</label>
              </div>
          </div>
            </a> </div>