<?php
$z[0]=Array("pagestyle","",0,88);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="0";
$z[0][4]['ddmaxwidth']="0";
$z[0][4]['row']="0";
$z[0][4]['col']="0";
$z[0][4]['value']="3";
$z[1]=Array("img"," /uploads/allimg/160123/1-160123230K8.jpg ",90,238);
$z[1][4]['ddimg']="/uploads/allimg/160123/1-160123230K8-lp.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="800";
$z[1][4]['height']="466";
$z[2]=Array("img"," /uploads/allimg/160123/1-160123231037.jpg ",240,390);
$z[2][4]['ddimg']="/uploads/allimg/160123/1-160123231037-lp.jpg";
$z[2][4]['text']="";
$z[2][4]['width']="800";
$z[2][4]['height']="739";

?>