<?php
$z[0]=Array("pagestyle","",0,88);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="0";
$z[0][4]['ddmaxwidth']="0";
$z[0][4]['row']="0";
$z[0][4]['col']="0";
$z[0][4]['value']="3";
$z[1]=Array("img"," /uploads/allimg/160127/1-16012H25P7.jpg ",90,236);
$z[1][4]['ddimg']="/uploads/allimg/160127/1-16012H25P7-lp.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="800";
$z[1][4]['height']="531";
$z[2]=Array("img"," /uploads/allimg/160127/1-16012H25P9.jpg ",238,384);
$z[2][4]['ddimg']="/uploads/allimg/160127/1-16012H25P9-lp.jpg";
$z[2][4]['text']="";
$z[2][4]['width']="800";
$z[2][4]['height']="531";
$z[3]=Array("img"," /uploads/allimg/160127/1-16012H25Q0.jpg ",386,532);
$z[3][4]['ddimg']="/uploads/allimg/160127/1-16012H25Q0-lp.jpg";
$z[3][4]['text']="";
$z[3][4]['width']="800";
$z[3][4]['height']="531";
$z[4]=Array("img"," /uploads/allimg/160127/1-16012H25Q2.jpg ",534,680);
$z[4][4]['ddimg']="/uploads/allimg/160127/1-16012H25Q2-lp.jpg";
$z[4][4]['text']="";
$z[4][4]['width']="800";
$z[4][4]['height']="531";
$z[5]=Array("img"," /uploads/allimg/160127/1-16012H25Q3.jpg ",682,828);
$z[5][4]['ddimg']="/uploads/allimg/160127/1-16012H25Q3-lp.jpg";
$z[5][4]['text']="";
$z[5][4]['width']="800";
$z[5][4]['height']="531";

?>