<?php
$z[0]=Array("pagestyle","",0,84);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="";
$z[0][4]['ddmaxwidth']="";
$z[0][4]['row']="";
$z[0][4]['col']="";
$z[0][4]['value']="1";
$z[1]=Array("img"," /uploads/allimg/180315/1-1P3150R127.jpg ",86,235);
$z[1][4]['ddimg']="/uploads/allimg/180315/1-1P3150R127.jpg";
$z[1][4]['text']="地段";
$z[1][4]['width']="800";
$z[1][4]['height']="686";
$z[2]=Array("img"," /uploads/allimg/180315/1-1P3150R128.jpg ",237,386);
$z[2][4]['ddimg']="/uploads/allimg/180315/1-1P3150R128.jpg";
$z[2][4]['text']="地段";
$z[2][4]['width']="800";
$z[2][4]['height']="450";

?>