<div class="newBox box">
            <div class="newBox-pic fl"> <a href="[field:arcurl/]"><img src="[field:litpic/]" alt="" width="160" height="120"></a> </div>
            <div class="newBox-info fr">
              <h4 class="newBox-info-tit"> <a href="[field:arcurl/]">[field:title/]</a></h4>
              <p class="newBox-info-sub">编辑：admin　　发布时间：[field:pubdate function=MyDate('y-m-d',@me)/]</p>
              <p class="newBox-info-preface"> [field:description/]...</p>
            </div>
          </div>