<a href="view.php?aid=[field:id/]">
  <dl>
    <dt><img class="scrollLoading" src="[field:litpic/]" /></dt>
    <dd> <strong class="thlist_name">[field:title/]<!--<em class="tuan_ico"></em>--></strong>
      <div class="you_like_infor"> <span class="f-left">[[field:typename/]]</span>
        <div class="price f-right">[field:junjia/]元/平</div>
        <div class="clear"></div>
      </div>
      
      <div class="discount">[field:zlhuxing/]</div>
    </dd>
  </dl>
  </a>