<field:pagestyle itemname="页面风格" type="number" isnull="true" default="2" rename="" notsend="1" />	
<field:imgurls itemname="图片集合" type="img" isnull="true" default="" rename="" page="split"/>	
<field:body itemname="项目介绍" autofield="0" notsend="0" type="htmltext" isnull="true" islist="0" default=""  maxlength="250" page=""></field:body>
<field:qijia itemname="起价" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:qijia>
<field:junjia itemname="均价" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:junjia>
<field:jiagequjian itemname="价格区间" autofield="1" notsend="0" type="select" isnull="true" islist="0" default="3000元以下,3000元-6000元,6000元-8000元,8000元以上"  maxlength="250" page="">
</field:jiagequjian>
<field:loupanleixing itemname="特色房产" autofield="1" notsend="0" type="select" isnull="true" islist="1" default="养老房,海景房,刚需房,特色别墅,温泉入户,打折优惠,年度热盘"  maxlength="250" page="">
</field:loupanleixing>
<field:kaipantime itemname="开盘时间" autofield="1" notsend="0" type="datetime" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:kaipantime>
<field:jiaofangtime itemname="交房时间" autofield="1" notsend="0" type="datetime" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:jiaofangtime>
<field:lopandizhi itemname="楼盘地址" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:lopandizhi>
<field:zuobiaox itemname="楼盘坐标" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:zuobiaox>
<field:zlhuxing itemname="主力户型" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:zlhuxing>
<field:tmaidian itemname="【团购】卖点" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:tmaidian>
<field:tyouhui itemname="【团购】优惠" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:tyouhui>
<field:djyouhui itemname="优惠条件" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:djyouhui>
<field:kaifaman itemname="开发商" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:kaifaman>
<field:guihuaarea itemname="规划面积" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:guihuaarea>
<field:jianzhuarea itemname="建筑面积" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:jianzhuarea>
<field:totalbuilding itemname="总栋数" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:totalbuilding>
<field:guihuabuilding itemname="规划户数" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:guihuabuilding>
<field:decoratexk itemname="装修情况" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:decoratexk>
<field:plotratio itemname="容积率" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:plotratio>
<field:lvhuarate itemname="绿化率" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:lvhuarate>
<field:wuyegs itemname="物业公司" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:wuyegs>
<field:wuyef itemname="物业费" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:wuyef>
<field:gongjiaolx itemname="公交路线" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:gongjiaolx>
<field:license itemname="预售许可证" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:license>
<field:salesoffices itemname="售楼处" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:salesoffices>
<field:slctel itemname="售楼处电话" autofield="1" notsend="0" type="text" isnull="true" islist="1" default="400-888-9999"  maxlength="250" page="">
</field:slctel>
<field:zbshool itemname="[周边设施]学校" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:zbshool>
<field:zbgouwu itemname="[周边设施]购物" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:zbgouwu>
<field:zbyiyuan itemname="[周边设施]医院" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:zbyiyuan>
<field:zbshenghua itemname="[周边设施]生活" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:zbshenghua>
<field:zbyule itemname="[周边设施]娱乐" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:zbyule>
<field:zbcanyin itemname="[周边设施]餐饮" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:zbcanyin>
<field:imgurls2 itemname="户型图" autofield="0" notsend="0" type="img" isnull="true" islist="0" default=""  maxlength="" page="">
</field:imgurls2>
