<?php
$z[0]=Array("pagestyle","",0,88);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="6";
$z[0][4]['ddmaxwidth']="0";
$z[0][4]['row']="5";
$z[0][4]['col']="3";
$z[0][4]['value']="3";
$z[1]=Array("img"," /uploads/allimg/160515/1-160515222945.png ",90,245);
$z[1][4]['ddimg']="/uploads/allimg/160515/1-160515222945-lp.png";
$z[1][4]['text']="62平";
$z[1][4]['width']="530";
$z[1][4]['height']="507";
$z[2]=Array("img"," /uploads/allimg/160830/1-160S0231635.jpg ",247,395);
$z[2][4]['ddimg']="/uploads/allimg/160830/1-160S0231635-lp.jpg";
$z[2][4]['text']="";
$z[2][4]['width']="600";
$z[2][4]['height']="400";

?>