<?php
$z[0]=Array("field","",222,241);
$z[0][4]['name']="title";
$z[1]=Array("global","",242,268);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("channel","\r\n      <li><a href=\"list.php?tid=[field:id/]\">[field:typename/]</a></li>\r\n      ",1112,1242);
$z[2][4]['type']="top";
$z[2][4]['row']="10";
$z[3]=Array("field","",1371,1390);
$z[3][4]['name']="title";
$z[4]=Array("field","",1416,1438);
$z[4][4]['name']="typename";
$z[5]=Array("field","",1450,1509);
$z[5][4]['name']="pubdate";
$z[5][4]['function']="MyDate('Y年m月d日',@me)";
$z[6]=Array("field","",1547,1574);
$z[6][4]['name']="phpurl";
$z[7]=Array("field","",1598,1621);
$z[7][4]['name']="id";
$z[8]=Array("field","",1626,1650);
$z[8][4]['name']="mid";
$z[9]=Array("field","",1761,1779);
$z[9][4]['name']="body";
$z[10]=Array("include","",1799,1838);
$z[10][4]['filename']="footer_m.htm";

?>