{dede:pagestyle maxwidth='800' pagepicnum='0' ddmaxwidth='0' row='0' col='0' value='3'/}
{dede:img ddimg='/uploads/allimg/180315/1-1P315101453-lp.jpg' text='认筹2-4万，如果买四楼成功，可冲低2万' width='1920' height='1440'} /uploads/allimg/180315/1-1P315101453.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/180315/1-1P315101454-lp.jpg' text='认筹2-4万，如果买四楼成功，可冲低2万' width='1920' height='1440'} /uploads/allimg/180315/1-1P315101454.jpg {/dede:img}
