<li>
          <div class="imgdiv">
            <div class="icons"> <i class="iconHaowu"></i> <i class="iconPrefer"></i> </div>
            <a href="[field:arcurl/]" target="_blank"> <img src="[field:litpic/]" alt=""> </a> </div>
          <div class="proptydetails">
            <h1><a href="[field:arcurl/]" target="_blank">[field:title/]</a> </h1>
            <div class="information">
              <div class="detail">
                <table>
                  <tbody>
                    <tr>
                      <th><i></i>楼盘位置 : [field:typename/]</th>
                      <td>均价： [field:junjia/]元/平米 </td>
                      <td class="openDate" title="">开盘日期：[field:pubdate function=MyDate('y-m-d',@me)/]</td>
                    </tr>
                  </tbody>
                </table>
                <dl>
                  <dt>海南易居团购优惠活动：</dt>
                  <dd>[field:tmaidian/]</dd>
                </dl>
                <div class="tolearn"> <a target="_blank" href="[field:arcurl/]">了解详情<i></i></a> </div>
              </div>
              <div class="data">
                <h2><strong> [field:click/] </strong>人推荐</h2>
                
                <input class="recommend login" type="submit" onclick="window.open('http://wpa.qq.com/msgrd?v=3&uin=541475789&site=qq&menu=yes')" value="在线咨询">
                
             
                <a class="tobuy login" data-reveal-id="myModal">我要看房</a>
                
              </div>
            </div>
            
          </div>
        </li>