<?php
$z[0]=Array("arcurl","",152,167);
$z[1]=Array("litpic","",196,211);
$z[2]=Array("arcurl","",298,313);
$z[3]=Array("title","",331,345);
$z[4]=Array("typename","",558,575);
$z[5]=Array("junjia","",618,633);
$z[6]=Array("pubdate","",718,763);
$z[6][4]['function']="MyDate('y-m-d',@me)";
$z[7]=Array("tmaidian","",957,974);
$z[8]=Array("arcurl","",1067,1082);
$z[9]=Array("click","",1201,1215);

?>