<?php
$z[0]=Array("top","\r\n  <m:item name='网站栏目管理' link='catalog_main.php' ischannel='1' addalt='创建栏目' linkadd='catalog_add.php?listtype=all' rank='t_List,t_AccList' target='main' />\r\n    <m:item name='普通文章' ischannel='1' link='content_list.php?channelid=1' linkadd='article_add.php?channelid=1' channelid='1' rank='' target='main' />\r\n\r\n  <m:item name='所有档案列表' link='content_list.php' rank='a_List,a_AccList' target='main' />\r\n  <m:item name='内容模型管理'  link='mychannel_main.php' rank='c_List' target='main' />\r\n  <m:item name='TAG标签管理' link='tags_main.php' rank='sys_Keyword' target='main' />\r\n  \r\n  \r\n",53,751);
$z[0][4]['item']="1_";
$z[0][4]['name']="内容管理";
$z[0][4]['display']="block";
$z[1]=Array("top","\r\n  \r\n  <m:item name='一键更新网站' link='makehtml_all.php' rank='sys_MakeHtml' target='main' />\r\n  <m:item name='更新系统缓存' link='sys_cache_up.php' rank='sys_ArcBatch' target='main' />\r\n  <m:item name='更新主页HTML' link='makehtml_homepage.php' rank='sys_MakeHtml' target='main' />\r\n  <m:item name='更新栏目HTML' link='makehtml_list.php' rank='sys_MakeHtml' target='main' />\r\n  <m:item name='更新文档HTML' link='makehtml_archives.php' rank='sys_MakeHtml' target='main' />\r\n  \r\n",755,1321);
$z[1][4]['item']="1_";
$z[1][4]['name']="生成管理";
$z[1][4]['display']="block";
$z[2]=Array("top","\r\n  <m:item name='系统基本参数' link='sys_info.php' rank='sys_Edit' target='main' />\r\n  <m:item name='系统用户管理' link='sys_admin_user.php' rank='sys_User' target='main' />\r\n  <m:item name='数据库备份/还原' link='sys_data.php' rank='sys_Data' target='main' />\r\n  <m:item name='验证安全设置' link='sys_safe.php' rank='sys_verify' target='main' />\r\n  <m:item name='图片水印设置' link='sys_info_mark.php' rank='sys_Edit' target='main' />\r\n  <m:item name='自定义文档属性' link='content_att.php' rank='sys_Att' target='main' />\r\n  <m:item name='SQL命令行工具' link='sys_sql_query.php' rank='sys_Data' target='main' />\r\n",1325,2044);
$z[2][4]['item']="1_";
$z[2][4]['name']="系统设置";
$z[2][4]['display']="none";
$z[3]=Array("top","\r\n  <m:item name='友情链接管理' link='friendlink_main.php' target='main' />\r\n  <m:item name='默认模板管理' link='templets_main.php' rank='temp_All' target='main'/>\r\n  <m:item name='客户留言管理' link='diy_main.php' rank='c_List' target='main'/>\r\n  <m:item name='幻灯片管理' link='ppt_main.php' rank='c_List' target='main'/>\r\n  <m:item name='广告位管理' link='ad_main.php' rank='c_List' target='main'/>\r\n  <m:item name='搜索关键词维护' link='search_keywords_main.php' rank='c_List' target='main'/>\r\n  \r\n  <m:item name='文档关键词维护' link='article_keywords_main.php' rank='sys_Keyword' target='main' />\r\n  <m:item name='重复文档检测' link='article_test_same.php' rank='sys_ArcBatch' target='main' />\r\n",2052,2861);
$z[3][4]['item']="1_";
$z[3][4]['name']="网站运维";
$z[3][4]['display']="none";

?>