
<field:bm_fmname itemname="姓名" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:bm_fmname>

<field:bm_fmtel itemname="手机" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:bm_fmtel>

<field:bm_fmbeizhu itemname="备注" autofield="1" type="multitext" isnull="true" default=""  maxlength="250" page="">
</field:bm_fmbeizhu>

<field:mytime itemname="报名时间" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:mytime>


<field:dytime itemname="订阅时间" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:dytime>


