<?php
$z[0]=Array("pagestyle","",0,84);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="";
$z[0][4]['ddmaxwidth']="";
$z[0][4]['row']="";
$z[0][4]['col']="";
$z[0][4]['value']="3";
$z[1]=Array("img"," /uploads/allimg/180315/1-1P3150S011.jpg ",86,250);
$z[1][4]['ddimg']="/uploads/allimg/180315/1-1P3150S011.jpg";
$z[1][4]['text']="89平方米均价4700";
$z[1][4]['width']="800";
$z[1][4]['height']="450";

?>