<div class="hot-item">
                                    <a href="[field:arcurl/]" target="_blank">
                                        <span class="order order-top[field:global.autoindex/]">[field:global.autoindex/]</span>
                                        <span class="houseName" title="[field:title/]">[field:title/] </span>
                                        <span class="unit pull-right">[field:qijia/]元/㎡</span></a>
                                </div>