<?php
$z[0]=Array("pagestyle","",0,84);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="";
$z[0][4]['ddmaxwidth']="";
$z[0][4]['row']="";
$z[0][4]['col']="";
$z[0][4]['value']="1";
$z[1]=Array("img"," /uploads/allimg/180315/1-1P3150QH7.jpg ",86,251);
$z[1][4]['ddimg']="/uploads/allimg/180315/1-1P3150QH7.jpg";
$z[1][4]['text']="151平方米均价5000";
$z[1][4]['width']="1080";
$z[1][4]['height']="1080";
$z[2]=Array("img"," /uploads/allimg/180315/1-1P3150QH7-50.jpg ",253,424);
$z[2][4]['ddimg']="/uploads/allimg/180315/1-1P3150QH7-50.jpg";
$z[2][4]['text']="151平方米均价5000";
$z[2][4]['width']="1920";
$z[2][4]['height']="1080";

?>