{dede:pagestyle maxwidth='800' pagepicnum='' ddmaxwidth='' row='' col='' value='1'/}
{dede:img ddimg='/uploads/allimg/180315/1-1P3150QH7.jpg' text='151平方米均价5000' width='1080' height='1080'} /uploads/allimg/180315/1-1P3150QH7.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/180315/1-1P3150QH7-50.jpg' text='151平方米均价5000' width='1920' height='1080'} /uploads/allimg/180315/1-1P3150QH7-50.jpg {/dede:img}
