<?php
$z[0]=Array("field","(@me==\"\")? @me=\" class='hover' \":@me=\"\";",236,326);
$z[0][4]['name']="typeid";
$z[0][4]['runphp']="yes";
$z[1]=Array("channel","<li><a href=\"[field:typelink/]\" class=\"\" target=\"_self\">[field:typename/]</a></li>",362,566);
$z[1][4]['type']="top";
$z[1][4]['row']="3";
$z[1][4]['currentstyle']="<li class='hover'><a href='~typelink~'>~typename~</a></li>";
$z[2]=Array("global","",728,753);
$z[2][4]['name']="cfg_cmsurl";
$z[3]=Array("global","",1316,1339);
$z[3][4]['name']="cfg_tels";

?>