<?php
$z[0]=Array("global","",225,251);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("channel","\r\n              <li><a href=\"list.php?tid=[field:id/]\">[field:typename/]</a></li>\r\n              ",1087,1232);
$z[1][4]['type']="top";
$z[1][4]['row']="2";
$z[2]=Array("channel","\r\n		  <li><a href='list.php?tid=[field:id/]' [field:rel/]>[field:typename/]</a></li>\r\n          ",1425,1682);
$z[2][4]['type']="son";
$z[2][4]['typeid']="1";
$z[2][4]['row']="10";
$z[2][4]['currentstyle']="<li><a class='active' href='list.php?tid=~id~' ~rel~><span>~typename~</span></a></li>";
$z[3]=Array("global","",2975,2998);
$z[3][4]['name']="cfg_tels";
$z[4]=Array("arclist","\r\n  <figure> \r\n    <a href=\"view.php?aid=[field:id/]\"> \r\n    <figcaption> <span class=\"color01\">[field:title/]</span> [field:info/]</figcaption>\r\n    </a> \r\n  </figure>\r\n ",3237,3470);
$z[4][4]['row']="4";
$z[4][4]['titlelen']="80";
$z[4][4]['typeid']="2";
$z[5]=Array("arclist","\r\n  <a href=\"view.php?aid=[field:id/]\">\r\n  <dl>\r\n    <dt><img class=\"scrollLoading\" src=\"[field:litpic/]\" /></dt>\r\n    <dd> <strong class=\"thlist_name\">[field:title/]<!--<em class=\"tuan_ico\"></em>--></strong>\r\n      <div class=\"you_like_infor\"> <span class=\"f-left\">[[field:typename/]]</span>\r\n        <div class=\"price f-right\">[field:junjia/]元/平</div>\r\n        <div class=\"clear\"></div>\r\n      </div>\r\n      \r\n      <div class=\"discount\">[field:zlhuxing/]</div>\r\n    </dd>\r\n  </dl>\r\n  </a> \r\n ",3631,4234);
$z[5][4]['pagesize']="10";
$z[5][4]['typeid']="1";
$z[5][4]['addfields']="hotcity,zlhuxing,junjia";
$z[5][4]['channelid']="2";
$z[6]=Array("include","",4250,4289);
$z[6][4]['filename']="footer_m.htm";

?>