<?php
$z[0]=Array("field","",254,273);
$z[0][4]['name']="title";
$z[1]=Array("global","",274,300);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",341,370);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",410,468);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("global","",1167,1195);
$z[4][4]['name']="cfg_mobileurl";
$z[5]=Array("field","",1209,1225);
$z[5][4]['name']="id";
$z[6]=Array("channel","\r\n            <li class=\"menu-item\"><a href=\"[field:typeurl/]\">[field:typename/]</a></li>\r\n            ",1682,1913);
$z[6][4]['type']="son";
$z[6][4]['currentstyle']="<li class='menu-item thisclass'><a href='~typelink~'>~typename~</a></li>";
$z[7]=Array("field","",2330,2351);
$z[7][4]['name']="content";

?>