<?php
$z[0]=Array("global","",222,248);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("channel","\r\n              <li><a href=\"list.php?tid=[field:id/]\">[field:typename/]</a></li>\r\n              ",2014,2159);
$z[1][4]['type']="top";
$z[1][4]['row']="2";
$z[2]=Array("channel","\r\n		  <li><a href='list.php?tid=[field:id/]' [field:rel/]>[field:typename/]</a></li>\r\n          ",2672,2918);
$z[2][4]['type']="son";
$z[2][4]['row']="10";
$z[2][4]['currentstyle']="<li><a class='active' href='list.php?tid=~id~' ~rel~><span>~typename~</span></a></li>";
$z[3]=Array("list","\r\n<a href=\"view.php?aid=[field:id/]\">\r\n  <dl>\r\n    <dt><img class=\"scrollLoading\"  src=\"[field:litpic/]\"/></dt>\r\n    <dd> <strong class=\"thlist_name\">[field:title/]<!--<em class=\"tuan_ico\"></em>--></strong>\r\n      <div class=\"you_like_infor\"> <span class=\"f-left\">[[field:typename/]]</span>\r\n        <div class=\"price f-right\">[field:qijia/]元/㎡</div>\r\n        <div class=\"clear\"></div>\r\n      </div>\r\n      <p>[field:id function=GetTags(@me)/] </p>\r\n      <div class=\"discount\">[field:zlhuxing/]</div>\r\n    </dd>\r\n  </dl>\r\n  </a> \r\n",3066,3639);
$z[3][4]['pagesize']="10";
$z[4]=Array("pagelist","",3828,3887);
$z[4][4]['listitem']="pre,next,index,end";
$z[4][4]['listsize']="5";
$z[5]=Array("include","",3909,3948);
$z[5][4]['filename']="footer_m.htm";

?>