<?php
$z[0]=Array("global","",222,248);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("channel","\r\n      <li><a href=\"list.php?tid=[field:id/]\">[field:typename/]</a></li>\r\n      ",1942,2072);
$z[1][4]['type']="top";
$z[1][4]['row']="10";
$z[2]=Array("list"," <a href=\"view.php?aid=[field:id/]\">\r\n  <figure> <img class=\"scrollLoading\" src=\"[field:litpic/]\"  height=\"80\" width=\"120\">\r\n    <figcaption>[field:title/]...</figcaption>\r\n    <time>[field:pubdate function=MyDate('y年-m月-d日',@me)/]</time>\r\n  </figure>\r\n  </a> ",2236,2539);
$z[2][4]['pagesize']="10";
$z[3]=Array("pagelist","",2722,2781);
$z[3][4]['listitem']="pre,next,index,end";
$z[3][4]['listsize']="5";

?>