<?php  exit();
/*
Page: /
Error: DedeCms错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
Time2018-03-14 14:28:45
*/
?>
<?php  exit();
/*
Page: /index.php
Error: DedeCms错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
Time2018-03-14 17:33:11
*/
?>
<?php  exit();
/*
Page: /index.php
Error: DedeCms错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
Time2018-03-14 18:59:31
*/
?>
